#include<graphics.h>
#include<dos.h>
	void printpiece(int posx_r1, int posy_r1,int posx_r2,int posy_r2,int
			posx_r3,int posy_r3,int posx_r4,int posy_r4,int posx_g1,int posy_g1,int posx_g2,int
			posy_g2,int posx_g3,int posy_g3,int posx_g4,int posy_g4,int posx_y1,int posy_y1,int
			posx_y2,int posy_y2,int posx_y3,int posy_y3,int posx_y4,int posy_y4,int posx_b1,int
			posy_b1,int posx_b2,int posy_b2,int posx_b3,int posy_b3,int posx_b4,int posy_b4)
	{

		framework();
		if(posx_r1>15 && posy_r1==225)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_r1,posy_r1,15);
			floodfill(posx_r1,posy_r1,8);
		}else
		{
		setcolor(RED);
		setfillstyle(SOLID_FILL,RED);
		circle(posx_r1,posy_r1,15);
		floodfill(posx_r1,posy_r1,RED);
		}
		setcolor(0);
		outtextxy(posx_r1,posy_r1,"R1");
		if(posx_r2>15 && posy_r2==225)
		{
				setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_r2,posy_r2,15);
			floodfill(posx_r2,posy_r2,8);
		}
		else
		{
		setcolor(RED);
		setfillstyle(SOLID_FILL,RED);
		circle(posx_r2,posy_r2,15);
		floodfill(posx_r2,posy_r2,RED);
		}
		setcolor(0);
		outtextxy(posx_r2,posy_r2,"R2");
		if(posx_r3>15 && posy_r3==225)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_r3,posy_r3,15);
			floodfill(posx_r3,posy_r3,8);
		}
		else
		{
			setcolor(RED);
			setfillstyle(SOLID_FILL,RED);
			circle(posx_r3,posy_r3,15);
			floodfill(posx_r3,posy_r3,RED);
		}
		setcolor(0);
		outtextxy(posx_r3,posy_r3,"R3");
		if(posx_r4>15 && posy_r4==225)
		{
				setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_r4,posy_r4,15);
			floodfill(posx_r4,posy_r4,8);
		}
		else
		{
			setcolor(RED);
			setfillstyle(SOLID_FILL,RED);
			circle(posx_r4,posy_r4,15);
			floodfill(posx_r4,posy_r4,RED);
		}
		setcolor(0);
		outtextxy(posx_r4,posy_r4,"R4");
		if(posx_g1==225 && posy_g1>=15)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_g1,posy_g1,15);
			floodfill(posx_g1,posy_g1,8);
		}
		else
		{
			setcolor(GREEN);
			setfillstyle(SOLID_FILL,GREEN);
			circle(posx_g1,posy_g1,15);
			floodfill(posx_g1,posy_g1,GREEN);
		}
		setcolor(0);
		outtextxy(posx_g1-7,posy_g1-7,"G1");
			if(posx_g2==225 && posy_g2>=15)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_g2,posy_g2,15);
			floodfill(posx_g2,posy_g2,8);
		}
		else
		{
			setcolor(GREEN);
			setfillstyle(SOLID_FILL,GREEN);
			circle(posx_g2,posy_g2,15);
			floodfill(posx_g2,posy_g2,GREEN);
		}
		setcolor(0);
		outtextxy(posx_g2-7,posy_g2-7,"g2");
			if(posx_g3==225 && posy_g3>=15)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_g3,posy_g3,15);
			floodfill(posx_g3,posy_g3,8);
		}
		else
		{
			setcolor(GREEN);
			setfillstyle(SOLID_FILL,GREEN);
			circle(posx_g3,posy_g3,15);
			floodfill(posx_g3,posy_g3,GREEN);
		}
		setcolor(0);
		outtextxy(posx_g3-7,posy_g3-7,"g3");
			if(posx_g4==225 && posy_g4>=15)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_g4,posy_g4,15);
			floodfill(posx_g4,posy_g4,8);
		}
		else
		{
			setcolor(GREEN);
			setfillstyle(SOLID_FILL,GREEN);
			circle(posx_g4,posy_g4,15);
			floodfill(posx_g4,posy_g4,GREEN);
		}
		setcolor(0);
		outtextxy(posx_g4-7,posy_g4-7,"g4");
		if(posx_y1<435 && posy_y1==225)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_y1,posy_y1,15);
			floodfill(posx_y1,posy_y1,8);
		}
		else
		{
			setcolor(YELLOW);
			setfillstyle(SOLID_FILL,YELLOW);
			circle(posx_y1,posy_y1,15);
			floodfill(posx_y1,posy_y1,YELLOW);
		}
		setcolor(0);
		outtextxy(posx_y1-6,posy_y1-6,"Y1");
			if(posx_y2<435 && posy_y2==225)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_y2,posy_y2,15);
			floodfill(posx_y2,posy_y2,8);
		}
		else
		{
			setcolor(YELLOW);
			setfillstyle(SOLID_FILL,YELLOW);
			circle(posx_y2,posy_y2,15);
			floodfill(posx_y2,posy_y2,YELLOW);
		}
		setcolor(0);
		outtextxy(posx_y2-6,posy_y2-6,"Y2");
			if(posx_y3<435 && posy_y3==225)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_y3,posy_y3,15);
			floodfill(posx_y3,posy_y3,8);
		}
		else
		{
			setcolor(YELLOW);
			setfillstyle(SOLID_FILL,YELLOW);
			circle(posx_y3,posy_y3,15);
			floodfill(posx_y3,posy_y3,YELLOW);
		}
		setcolor(0);
		outtextxy(posx_y3-6,posy_y3-6,"Y3");
			if(posx_y4<435 && posy_y4==225)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_y4,posy_y4,15);
			floodfill(posx_y4,posy_y4,8);
		}
		else
		{
			setcolor(YELLOW);
			setfillstyle(SOLID_FILL,YELLOW);
			circle(posx_y4,posy_y4,15);
			floodfill(posx_y4,posy_y4,YELLOW);
		}
		setcolor(0);
		outtextxy(posx_y4-6,posy_y4-6,"Y4");
		if(posx_b1==225 && posy_b1<435)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_b1,posy_b1,15);
			floodfill(posx_b1,posy_b1,8);
		}
		else
		{
			setcolor(BLUE);
			setfillstyle(SOLID_FILL,BLUE);
			circle(posx_b1,posy_b1,15);
			floodfill(posx_b1,posy_b1,BLUE);
		}
		setcolor(0);
		outtextxy(posx_b1-6,posy_b1-6,"B1");
		if(posx_b2==225 && posy_b2<435)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_b2,posy_b2,15);
			floodfill(posx_b2,posy_b2,8);
		}
		else
		{
			setcolor(BLUE);
			setfillstyle(SOLID_FILL,BLUE);
			circle(posx_b2,posy_b2,15);
			floodfill(posx_b2,posy_b2,BLUE);
		}
		setcolor(0);
		outtextxy(posx_b2-6,posy_b2-6,"B2");
		if(posx_b3==225 && posy_b3<435)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_b3,posy_b3,15);
			floodfill(posx_b3,posy_b3,8);
		}
		else
		{
			setcolor(BLUE);
			setfillstyle(SOLID_FILL,BLUE);
			circle(posx_b3,posy_b3,15);
			floodfill(posx_b3,posy_b3,BLUE);
		}
		setcolor(0);
		outtextxy(posx_b3-6,posy_b3-6,"B3");
		if(posx_b4==225 && posy_b4<435)
		{
			setcolor(8);
			setfillstyle(SOLID_FILL,8);
			circle(posx_b4,posy_b4,15);
			floodfill(posx_b4,posy_b4,8);
		}
		else
		{
			setcolor(BLUE);
			setfillstyle(SOLID_FILL,BLUE);
			circle(posx_b4,posy_b4,15);
			floodfill(posx_b4,posy_b4,BLUE);
		}
		setcolor(0);
		outtextxy(posx_b4-6,posy_b4-6,"B4");
		delay(1500);
		cleardevice();
	}

